Use new setup from cachix/install-nix action and bump nix

diff --git a/niv-updater b/niv-updater
--- a/niv-updater
+++ b/niv-updater
@@ -25,12 +25,68 @@ setupPrerequisites() {
 
     # Check if some other step already installed Nix
     if [[ ! -d /nix/store ]] || ! nix --version >/dev/null 2>&1; then
-        sudo mkdir -p /etc/nix
-        # Workaround segfault: https://github.com/NixOS/nix/issues/2733
-        sudo sh -c 'echo "http2 = false" >> /etc/nix/nix.conf'
+        # Create a temporary workdir
+        workdir=$(mktemp -d)
+        trap 'rm -rf "$workdir"' EXIT
 
+        # Configure Nix
+        add_config() {
+            echo "$1" >>"$workdir/nix.conf"
+        }
+
+        # Workaround segfault: https://github.com/NixOS/nix/issues/2733
+        add_config "http2 = false"
+
+        add_config "max-jobs = auto"
+        if [[ $OSTYPE =~ darwin ]]; then
+            add_config "ssl-cert-file = /etc/ssl/cert.pem"
+        fi
+        # Allow binary caches for user
+        add_config "trusted-users = root ${USER:-}"
+        add_config "experimental-features = nix-command flakes"
+        # Add a GitHub access token.
+        # Token-less access is subject to lower rate limits.
+        # Use the default GitHub token if available.
+        # Skip this step if running an Enterprise instance. The default token there does not work for github.com.
+        if [[ -n ${GITHUB_TOKEN:-} && $GITHUB_SERVER_URL == "https://github.com" ]]; then
+            echo "::debug::Using the default GITHUB_TOKEN for github.com"
+            add_config "access-tokens = github.com=$GITHUB_TOKEN"
+        else
+            echo "::debug::Continuing without a GitHub access token"
+        fi
+        # Nix installer flags
+        installer_options=(
+            --no-channel-add
+            --darwin-use-unencrypted-nix-store-volume
+            --nix-extra-conf-file "$workdir/nix.conf"
+            --no-daemon
+        )
+
+        # "fix" the following error when running nix*
+        # error: the group 'nixbld' specified in 'build-users-group' does not exist
+        add_config "build-users-group ="
+        sudo mkdir -p /etc/nix
+        sudo chmod 0755 /etc/nix
+        sudo cp "$workdir/nix.conf" /etc/nix/nix.conf
+
+        # There is --retry-on-errors, but only newer curl versions support that
+        curl_retries=5
         # pin to ensure future upgrades do not interfere with the subsequent steps
-        sh <(curl -sSL https://releases.nixos.org/nix/nix-2.11.1/install) --no-daemon
+        while ! curl -sS -o "$workdir/install" -v --fail -L "https://releases.nixos.org/nix/nix-2.24.9/install"; do
+            sleep 1
+            ((curl_retries--))
+            if [[ $curl_retries -le 0 ]]; then
+                echo "curl retries failed" >&2
+                exit 1
+            fi
+        done
+
+        sh "$workdir/install" "${installer_options[@]}"
+
+        # Set paths
+        echo "/nix/var/nix/profiles/default/bin" >>"$GITHUB_PATH"
+        # new path for nix 2.14
+        echo "$HOME/.nix-profile/bin" >>"$GITHUB_PATH"
     fi
 
     echo 'Installing Nix - done'
